-- 
-- TABLE: PUNTO 
--

CREATE TABLE PUNTO(
    PUNTO_ID    DECIMAL(10, 0)    NOT NULL,
    X           DECIMAL(6, 2)     NOT NULL,
    Y           DECIMAL(6, 2)     NOT NULL,
    PRIMARY KEY (PUNTO_ID)
)ENGINE=INNODB
;

-- 
-- TABLE: CONTORNO 
--

CREATE TABLE CONTORNO(
    CONTORNO_ID    DECIMAL(10, 0)    NOT NULL,
    CLAVE          VARCHAR(30)       NOT NULL,
    PRIMARY KEY (CONTORNO_ID)
)ENGINE=INNODB
;

-- 
-- TABLE: PUNTO_CONTORNO 
--

CREATE TABLE PUNTO_CONTORNO(
    PUNTO_CONTORNO_ID    DECIMAL(10, 0)    NOT NULL,
    PUNTO_ID             DECIMAL(10, 0)    NOT NULL,
    CONTORNO_ID          DECIMAL(10, 0)    NOT NULL,
    PRIMARY KEY (PUNTO_CONTORNO_ID)
)ENGINE=INNODB
;

-- 
-- TABLE: PUNTO_CONTORNO 
--

ALTER TABLE PUNTO_CONTORNO ADD CONSTRAINT RefPUNTO12 
    FOREIGN KEY (PUNTO_ID)
    REFERENCES PUNTO(PUNTO_ID)
;

ALTER TABLE PUNTO_CONTORNO ADD CONSTRAINT RefCONTORNO22 
    FOREIGN KEY (CONTORNO_ID)
    REFERENCES CONTORNO(CONTORNO_ID)
;

-- 
-- TABLE: POLIGONO 
--

CREATE TABLE POLIGONO(
    POLIGONO_ID    DECIMAL(10, 0)    NOT NULL,
    CLAVE          VARCHAR(30)       NOT NULL,
    PRIMARY KEY (POLIGONO_ID)
)ENGINE=INNODB
;

-- 
-- TABLE: CONTORNO_POLIGONO 
--

CREATE TABLE CONTORNO_POLIGONO(
    CONTORNO_POLIGONO_ID    DECIMAL(10, 0)    NOT NULL,
    CONTORNO_ID             DECIMAL(10, 0)    NOT NULL,
    POLIGONO_ID             DECIMAL(10, 0)    NOT NULL,
    PRIMARY KEY (CONTORNO_POLIGONO_ID)
)ENGINE=INNODB
;

-- 
-- TABLE: CONTORNO_POLIGONO 
--

ALTER TABLE CONTORNO_POLIGONO ADD CONSTRAINT RefCONTORNO32 
    FOREIGN KEY (CONTORNO_ID)
    REFERENCES CONTORNO(CONTORNO_ID)
;

ALTER TABLE CONTORNO_POLIGONO ADD CONSTRAINT RefPOLIGONO42 
    FOREIGN KEY (POLIGONO_ID)
    REFERENCES POLIGONO(POLIGONO_ID)
;

-- 
-- TABLE: COMERCIO 
--

CREATE TABLE COMERCIO(
    COMERCIO_ID    DECIMAL(2, 0)     NOT NULL,
    CLAVE          VARCHAR(30)       NOT NULL,
    PUNTO_ID       DECIMAL(10, 0)    NOT NULL,
    PRIMARY KEY (COMERCIO_ID)
)ENGINE=INNODB
;

-- 
-- TABLE: COMERCIO 
--

ALTER TABLE COMERCIO ADD CONSTRAINT RefPUNTO62 
    FOREIGN KEY (PUNTO_ID)
    REFERENCES PUNTO(PUNTO_ID)
)ENGINE=INNODB
;

-- 
-- TABLE: PASILLO 
--

CREATE TABLE PASILLO(
    PASILLO_ID     DECIMAL(2, 0)     NOT NULL,
    CLAVE          VARCHAR(30)       NOT NULL,
    CONTORNO_ID    DECIMAL(10, 0)    NOT NULL,
    PRIMARY KEY (PASILLO_ID)
)ENGINE=INNODB
;

-- 
-- TABLE: PASILLO 
--

ALTER TABLE PASILLO ADD CONSTRAINT RefCONTORNO52 
    FOREIGN KEY (CONTORNO_ID)
    REFERENCES CONTORNO(CONTORNO_ID)
;

-- 
-- TABLE: EDIFICIO 
--

CREATE TABLE EDIFICIO(
    EDIFICIO_ID    DECIMAL(2, 0)     NOT NULL,
    CLAVE          VARCHAR(30)       NOT NULL,
    POLIGONO_ID    DECIMAL(10, 0)    NOT NULL,
    PRIMARY KEY (EDIFICIO_ID)
)ENGINE=INNODB
;

-- 
-- TABLE: EDIFICIO 
--

ALTER TABLE EDIFICIO ADD CONSTRAINT RefPOLIGONO72 
    FOREIGN KEY (POLIGONO_ID)
    REFERENCES POLIGONO(POLIGONO_ID)
;

-- 
-- TABLE: AVENIDA 
--

CREATE TABLE AVENIDA(
    AVENIDA_ID     DECIMAL(2, 0)     NOT NULL,
    CLAVE          VARCHAR(30)       NOT NULL,
    POLIGONO_ID    DECIMAL(10, 0)    NOT NULL,
    PRIMARY KEY (AVENIDA_ID)
)ENGINE=INNODB
;

-- 
-- TABLE: AVENIDA 
--

ALTER TABLE AVENIDA ADD CONSTRAINT RefPOLIGONO82 
    FOREIGN KEY (POLIGONO_ID)
    REFERENCES POLIGONO(POLIGONO_ID)
;

-- 
-- TABLE: AREA_VERDE 
--

CREATE TABLE AREA_VERDE(
    AREA_VERDE_ID    DECIMAL(10, 0)    NOT NULL,
    CLAVE            VARCHAR(30)       NOT NULL,
    POLIGONO_ID      DECIMAL(10, 0)    NOT NULL,
    PRIMARY KEY (AREA_VERDE_ID)
)ENGINE=INNODB
;

-- 
-- TABLE: AREA_VERDE 
--

ALTER TABLE AREA_VERDE ADD CONSTRAINT RefPOLIGONO92 
    FOREIGN KEY (POLIGONO_ID)
    REFERENCES POLIGONO(POLIGONO_ID)
;

-- 
-- TABLE: ESCUELA 
--

CREATE TABLE ESCUELA(
    ESCUELA_ID     DECIMAL(10, 0)    NOT NULL,
    CLAVE          VARCHAR(30)       NOT NULL,
    POLIGONO_ID    DECIMAL(10, 0)    NOT NULL,
    PRIMARY KEY (ESCUELA_ID)
)ENGINE=INNODB
;

-- 
-- TABLE: ESCUELA 
--

ALTER TABLE ESCUELA ADD CONSTRAINT RefPOLIGONO102 
    FOREIGN KEY (POLIGONO_ID)
    REFERENCES POLIGONO(POLIGONO_ID)
;

-- 
-- TABLE: CENTRO_COMERCIAL 
--

CREATE TABLE CENTRO_COMERCIAL(
    CENTRO_COMERCIAL_ID    DECIMAL(2, 0)     NOT NULL,
    CLAVE                  VARCHAR(30)       NOT NULL,
    POLIGONO_ID            DECIMAL(10, 0)    NOT NULL,
    PRIMARY KEY (CENTRO_COMERCIAL_ID)
)ENGINE=INNODB
;

-- 
-- TABLE: CENTRO_COMERCIAL 
--

ALTER TABLE CENTRO_COMERCIAL ADD CONSTRAINT RefPOLIGONO112 
    FOREIGN KEY (POLIGONO_ID)
    REFERENCES POLIGONO(POLIGONO_ID)
;


